cbtis128/Grupo5i/alumno/urls.py
from django.urls import path
from alumno import views

urlpatterns = [
    path('', views.Index_Vista, name='Index_vista'),
    path('alumno/<int:id>',views.Alumno_Vista, name='alumno_Vista')
]

cbtis128/Grupo5i/primaria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alumno.urls')),
]

cbtis128/Grupo5i/alumno/models.py
from django.db import models

# Create your models here.

class Alumno(models.Model):
    apaterno=models.CharField(max_length=50,verbose_name='Apellido Paterno')
    amaterno=models.CharField(max_length=50,verbose_name='Apellido Materno')
    nombre=models.CharField(max_length=100,verbose_name='Nombre (s)')
    fecha_nacimiento=models.DateField(verbose_name="Fecha de nacimiento", null=False,blank=False)
    fecha_ingreso=models.DateField(verbose_name="Fecha ingreso", null=False,blank=False)
    
    class Meta:
        db_table="Alumnos"
        verbose_name="Alumnos"
        verbose_name_plural="Alumnos"
        
    def __str__(self) -> str:
        return self.nombre
    
        

class Frase(models.Model): 
    comentario=models.TextField(verbose_name="Comentario", max_length=400)
    Alumno_fk=models.ForeignKey(Alumno, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name="Frase"
        verbose_name_plural= "Frase"
        

cbtis128/Grupo5i/alumno/views.py
from django.shortcuts import render,get_object_or_404
from .models import Alumno
# Create your views here.

def Index_Vista(request):
    misalumnos=Alumno.objects.all().order_by("id")
    return render (request, 'index.html',{"misalumnos":misalumnos})


def Alumno_Vista(request,id):
    alumno = get_object_or_404(Alumno,id=id)
    return render(request, 'alumno.html',{"objeto":alumno})

cbtis128/Grupo5i/alumno/templates/alumno.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>papayons</title>
    <link rel="stylesheet" href="{% static 'estilo.css' %}">
</head>
<body>
    <h1> Un alumno y ses mensos (comentarios) </h1>
    <h1>{{objeto.nombre}}</h1>
    <ul>
        {% for i in objeto.frase_set.all %}
        <li> {{ i.comentario}}</li>
        {% endfor %}
    </ul>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

cbtis128/Grupo5i/alumno/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Larrondo</title>
    <link rel="stylesheet" href="{% static 'estilo.css' %}">
</head>
<body>
    <center><h1>Esta es mi pagina</h1></center>
    <hr>
    <ul>
        {% for i in misalumnos %}
        <li> <a href="alumno/{{i.id}}">{{i.nombre}}</a></li>
        

        {% endfor %}
    </ul>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>